### ISSUE TITLE
error if there is already someone else registered on the signals

### ISSUE THREAD

**Issue by mcollina** [hemerajs/fastify-graceful-shutdown#2]
If you do not do this, and the application is using something else, you might get some very inconsistent behavior

**Comment by StarpTech** [comment]
Yes, I agree we should warn about itt. Do you prefer a log message or a throw the error?

**Comment by mcollina** [comment]
I think it should be an error, the plugin would not be usable otherwise.

**Comment by StarpTech** [comment]
Done.
