### ISSUE TITLE
`gracefulShutdown` is not a function

### ISSUE THREAD

**Issue by MyTotoro** [hemerajs/fastify-graceful-shutdown#20]
## 🐛 Bug Report

Seeing issues when trying to register graceful shutdown, node is complaining that it's not a function

## To Reproduce

See attachments
```'use strict'
const fastify = require('fastify')({
  logger: true
})

fastify.register(require('fastify-graceful-shutdown'));


// fastify.register(require('./our-first-route'))
fastify.gracefulShutdown((signal, next) => {
  console.log("fastify.gracefulShutdown")
  console.log(signal)
  next()
})

// Run the server!
fastify.listen(9000, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```
## Expected behavior

I expect it to work

## Your Environment

- *node version*: 14.16.0
- *fastify version*: >= 3.14.2
- *fastify graceful shutdown v*: >= 3.1.0
- *os*: Linux

![4](https://user-images.githubusercontent.com/3621921/115577483-77935000-a292-11eb-8d87-080b3a551816.png)
![3](https://user-images.githubusercontent.com/3621921/115577485-782be680-a292-11eb-82c9-bb7cfe391c00.png)

**Comment by mercxry** [comment]
I'm having the same issue, using typescript

```ts
import fastify from 'fastify';

const server = fastify({
    logger: true,
});

server.register(require('fastify-graceful-shutdown'));
server.gracefulShutdown((signal: string, next: () => void) => {
  next();
});
```

Error: `TS2339: Property 'gracefulShutdown' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'.`

**Comment by StarpTech** [comment]
Have a look at the example https://github.com/hemerajs/fastify-graceful-shutdown/blob/master/example.js. You have to register your handler in `fastify.after` because the bootstrapping process is asynchronously.

**Comment by StarpTech** [comment]
Readme was updated.

**Comment by aguegu** [comment]
For someone who run into this page, if this problem may caused if other plugins preposed may not get registered successfully.
