### ISSUE TITLE
Question: Why is it not possible to register multiple handlers?

### ISSUE THREAD

**Issue by bstenersen** [hemerajs/fastify-graceful-shutdown#36]
Hi,
could you explain why it is not possible to register multiple handlers?
Monitoring-Tools like Dynatrace register handlers as well, so it is not possible to use them along with this plugin.
Is it a technical limitation of NodeJS or is it not possible because of the implementation details of the plugin?

Thanks 
Björn

**Comment by StarpTech** [comment]
> Is it a technical limitation of NodeJS or is it not possible because of the implementation details of the plugin?

Because it is an anti-pattern. You should have one way to gracefully shutdown your server. I'm ok with logging a WARN rather than throwing an error. Would you like to create a PR?

**Comment by StarpTech** [comment]
Close due to inactivity.

**Comment by lboquillon** [comment]
I am interested in take back this idea, I can send a PR logging a warning rather than throwing the exception if you are ok with that.

**Comment by StarpTech** [comment]
Sounds good.
