### ISSUE TITLE
exit the process anyway after a certain timeout

### ISSUE THREAD

**Issue by mcollina** [hemerajs/fastify-graceful-shutdown#4]
As titled, in some bad situations the close sequence might be stuck

**Comment by StarpTech** [comment]
Do you know the cases?  It's a bug or just a bad constellation?

**Comment by mcollina** [comment]
sockets to dbs (or similar) not closing correctly, persistent websockets, some strange error conditions (automatic reconnects), and other bits.
Doing a proper shutdown in 100% of the cases is __very__ hard.

**Comment by StarpTech** [comment]
Reopen if you find any issue.
