### ISSUE TITLE
logger.flush is not a function

### ISSUE THREAD

**Issue by magiclen** [hemerajs/fastify-graceful-shutdown#43]
## Problem

When setting Fastify's logger option to `false`, an error is thrown when Fastify is terminated. The error message is `TypeError: logger.flush is not a function`.

## Steps to Reproduce

1. Set Fastify's logger option to `false` in the configuration.
1. Start the Fastify app and use <kbd>ctrl + c</kbd> to cancel it.
1. Observe the error thrown referencing **fastify-graceful-shutdown/index.js:45:14**.

**Comment by StarpTech** [comment]
We don't expect that someone disables the logger. It is stated in the README that we rely on it. I'd open an issue on fastify. The best solution would be to enable a noop implementation when `logger: false` instead of dealing with undefined.

**Comment by StarpTech** [comment]
Fixed in https://github.com/hemerajs/fastify-graceful-shutdown/releases/tag/v3.5.3
