### ISSUE TITLE
fastify.logger => fastify.log

### ISSUE THREAD

**Issue by noTruth** [hemerajs/fastify-graceful-shutdown#7]
[Here](https://github.com/hemerajs/fastify-graceful-shutdown/blob/master/index.js#L7) contains old wording. After this [commit](https://github.com/fastify/fastify/commit/8c0938bb9dc49fb574a69867282fc0705adfe71d), `logger` was renamed to `log`.
Thank you in advance)

**Comment by ansarizafar** [comment]
Please fix this issue.
